name: dev
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  test:
    uses: ./.github/workflows/_test.yml
    with:
      inputs-hoge: 'test-hoge'

  build:
    needs: test
    uses: ./.github/workflows/_build.yml
    with:
      inputs-hoge: 'build-hoge'

  regist:
    needs: build
    uses: ./.github/workflows/_regist.yml
    with:
      inputs-hoge: 'regist-hoge'
