name: dev
on:
  workflow_dispatch:
    inputs:
      target:
        type: choice
        description: Deploy target
        required: true
        options:
          - pre-dev
          - dev
          - all
jobs:
  test:
    uses: ./.github/workflows/_test.yml
    with:
      target: ${{ github.event.inputs.target }}"
